# Generated by Django 5.2.4 on 2025-09-06 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, unique=True)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('entity_description', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('INCOME_SOURCE', 'Source of income')], default='SUPPLIER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('exchange_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges_out', to='accounts.account')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges_from', to='core.currency')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges_in', to='accounts.account')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges_to', to='core.currency')),
            ],
            options={
                'ordering': ['-exchange_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_against_base', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date', models.DateField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_currency_rates', to='core.currency')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
            options={
                'unique_together': {('currency', 'base_currency', 'date')},
            },
        ),
    ]
