# Generated by Django 5.2.4 on 2025-08-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('INCOME_SOURCE', 'Source of income')], default='SUPPLIER', max_length=20),
        ),
    ]
