# Generated by Django 5.2.4 on 2025-08-27 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entity_entity_type'),
        ('investments', '0002_auto_categories'),
        ('records', '0003_alter_record_options_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='investment',
            name='inflow_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_inflow', to='records.record'),
        ),
        migrations.AddField(
            model_name='investment',
            name='outflow_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_outflow', to='records.record'),
        ),
    ]
