# Generated by Django 5.2.4 on 2025-08-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
