# Generated by Django 5.2.4 on 2025-08-21 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
