# Generated by Django 5.2.4 on 2025-10-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_type',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_category_sub',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null = global category, not tied to a specific user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null = global subcategory, not tied to a specific user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'category_name', 'category_type'), name='unique_category_per_user_or_global'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'user', 'subcategory_name'), name='unique_subcategory_per_category_user_or_global'),
        ),
    ]
