# Generated by Django 5.2.4 on 2026-03-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_category_unique_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_name', models.CharField(max_length=100)),
                ('finance_code', models.CharField(max_length=50, unique=True)),
                ('affects_balance', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['finance_name'],
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='financial_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='records.financialtype'),
        ),
    ]
